version: '3'

services:

  database:
    image: 'postgres:latest'
    container_name: database
    environment:
      - POSTGRES_PASSWORD=pass123

  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - '6969:6969'
    restart: on-failure
    container_name: todoa-app
    environment:
      - DEMON=on
      - PGUSER=postgres
      - PGHOST=database
      - PGDATABASE=postgres
      - PGPASSWORD=pass123
      - PGPORT=5432
    volumes:
      - './:/app'
